export enum RoleEnum {
  SUPERUSER = 'SUPERUSER',
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum PermissionEnum {
  // User permissions
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_LIST = 'USER_LIST',

  // Role permissions
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_LIST = 'ROLE_LIST',

  // Permission permissions
  PERMISSION_CREATE = 'PERMISSION_CREATE',
  PERMISSION_READ = 'PERMISSION_READ',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  PERMISSION_DELETE = 'PERMISSION_DELETE',
  PERMISSION_LIST = 'PERMISSION_LIST',
}

