version: '3.9'

volumes:
  postgres-data:
  redis-data:
  minio-data:

networks:
  starter-network:
    name: starter-network

services:
  postgres:
    extends:
      file: _docker-compose.base.yaml
      service: postgres
    networks:
      - starter-network

  redis:
    extends:
      file: _docker-compose.base.yaml
      service: redis
    networks:
      - starter-network

  minio:
    extends:
      file: _docker-compose.base.yaml
      service: minio
    networks:
      - starter-network

  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: starter-backend
    env_file: ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      - starter-network

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.web
    container_name: starter-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - starter-network
