FROM node:20-alpine

WORKDIR /app

# Копируем root файлы
COPY package*.json ./
COPY .npmrc ./
COPY tsconfig.json ./
COPY turbo.json ./

# Копируем packages
COPY packages ./packages

# Копируем web приложение
COPY apps/web ./apps/web

# Устанавливаем зависимости
RUN npm ci

# Собираем Web через turbo
RUN npm run build -- --filter=web

# Переходим в директорию web для запуска
WORKDIR /app/apps/web

EXPOSE 3000

CMD ["npm", "start"]
